apiVersion: v1
kind: Service
metadata:
  name: casino-frontend
  namespace: vidalcasino
spec:
  type: LoadBalancer
  selector:
    app: casino-frontend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP